## --------------------------------------------------------
## dpsFramework _config based on minima theme. (2017-2022)
## -------------------------------------------------------
theme: minima

show_excerpts: false
google_analytics: false

plugins:
 - jekyll-toc
 - jekyll-feed
 - jekyll-seo-tag
## - jekyll-paginate


markdown: kramdown


toc:
  min_level: 1
  max_level: 4
  ordered_list: false # default is false

github:
  owner_url: "https://github.com/dpsframework"
  repository_url: "https://github.com/dpsframework"
  owner_name: "dpsframework"
  project_tagline: "2.1"
  name: github
  is_project_page: true
  repository_name: dpsframework



## --------------------------------------------------------
## Web collections
## --------------------------------------------------------
title:
  en: 'dpsFramework project'
  es: 'Proyecto dpsFramework'


subtitle:
  en: 'Distributed Problem-Solving JADE Agents'
  es: 'Agentes JADE para resolución de problemas distribuidos'


baseurl:  ''
url:      'https://dpsframework.org'
hard_url: 'https://dpsframework.org'

collections:
  papers:
    output: true
    label: papers
  proposals:
    output: true
    label: proposals
  guides:
    output: true
    sort_by: chapter
    label: guides

defaults:
  - scope:
      path: ""
      type: "papers"
    values:
      layout: "paper"
  - scope:
      path: ""
      type: "proposals"
    values:
      layout: "proposal"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
    values:
      layout: "default"

## {{ site.collections | where: "label", "myCollection" | first }}

## --------------------------------------------------------
## Language control
## --------------------------------------------------------
lang: es

index:
  en: index.html
  es: index_es.html

feed:
  en: /feed.xml
  es: /feed_es.xml





## --------------------------------------------------------
## Jekyll minima
## --------------------------------------------------------
author:
  name:  'DpsFramework project'
  email: 'info@dpsframework.org'
  collabratech: 'https://ieee-collabratec.ieee.org/app/p/FranciscoAguayo115080'



minima:
  date_format: "%b %-d, %Y"
  skin: classic

  social_links:
    twitter: unileon
    github:  dpsframework
    # devto: 
    # dribbble: 
    facebook: unileon
    # flickr:   
    # instagram: 
    # linkedin: 
    # pinterest: 
    youtube: universidaddeleon
    # youtube_channel:
    # youtube_channel_name:
    # telegram: 
    # googleplus: +
    # microdotblog: 
    # keybase: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: example.com
    # - username: 
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: 
    #   instance: example.com
    # - username: 
    #   instance: example.com



