## --------------------------------------------------------
## dpsFramework _config based on minima theme. (2017-2022)
## -------------------------------------------------------
theme: minima


## Main domain: dpsFramework.github
## -------------------------------------------------
baseurl:  ''
url:      'https://dpsframework.org'
hard_url: 'https://dpsframework.org'


title:    'dpsFramework project: Distributed Production-Systems on JADE platform'

subtitle: 'dpsFramework project aims to maintain the compatibility of JADE distributed problem-solving agents (PS-Agents) and their connection to their integrated autonomous Expert Systems. This project also incorporates proposals, with proven solutions, to adapt: JADE 4.5.4 (2022) and its FIPA module implemented with CORBA libraries; and CLIPSJNI for CLIPS-6.31 or CLIPS-6.40, as well as core of JESS Rule-Based engine.'

author:
  name: pacoaguayo
  email: info@dpsframework.org

description: 'dpsFramework project aims to maintain the compatibility of JADE distributed problem-solving agents (PS-Agents) and their connection to their integrated autonomous Expert Systems. This project also incorporates proposals, with proven solutions, to adapt: JADE 4.5.4 (2022) and its FIPA module implemented with CORBA libraries; and CLIPSJNI for CLIPS-6.31 or CLIPS-6.40, as well as core of JESS Rule-Based engine.'

lang:   es
index:  index.html
feed:
  en: /feed_en.xml
  es: /feed.xml


show_excerpts: false
google_analytics: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 
markdown: kramdown


github:
  owner_url: "https://github.com/dpsframework"
  repository_url: "https://github.com/dpsframework"
  owner_name: dpsframework
  project_tagline: "1.8"
  name: dpsframework
  is_project_page: true
  repository_name: dpsframework




## --------------------------------------------------------
## Site dpsFramework collections
## --------------------------------------------------------
collections:
  papers:
    output: true
    label: papers
  proposals:
    output: true
    label: proposals
  guides:
    output: true
    sort_by: chapter
    label: guides
  notes:
    output: true
    label: notes

## {{ site.collections | where: "label", "proposals" | first }}
## ------------------------------------------------------------
defaults:
  - scope:
      path: ""
      type: "papers"
    values:
      layout: "paper"
  - scope:
      path: ""
      type: "proposals"
    values:
      layout: "proposal"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "drafts/**/*"
    values:
      sitemap: true


## --------------------------------------------------------
## Jekyll minima
## --------------------------------------------------------
author:
  name:  'DpsFramework project'
  email: 'info@dpsframework.org'
  collabratech: 'https://ieee-collabratec.ieee.org/app/p/FranciscoAguayo115080'


minima:
  date_format: "%b, %Y"  # "%b %-d, %Y"
  skin: classic

  social_links:
    twitter: unileon
    github:  dpsframework
    # devto: 
    # dribbble: 
    facebook: unileon
    # flickr:   
    # instagram: 
    # linkedin: 
    # pinterest: 
    youtube: universidaddeleon
    # youtube_channel:
    # youtube_channel_name:
    # telegram: 
    # googleplus: +
    # microdotblog: 
    # keybase: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: example.com
    # - username: 
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: 
    #   instance: example.com
    # - username: 
    #   instance: example.com


